---
version: '2'
services:
  broker-2:
    image: confluentinc/cp-kafka:latest
    hostname: broker
    container_name: broker-2
    ports:
      - "29092:29092"
      - "9092:9092"
      - "39092:39092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: '34.74.80.207:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT #, SSL_EXTERNAL:SSL
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092, PLAINTEXT_EXTERNAL://131.247.169.152:39092 #, SSL_EXTERNAL://34.74.80.207:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    # volumes:
    #   - ${KAFKA_SSL_SECRETS_DIR}:/etc/kafka/secrets
