---
version: '2'
services:
  zoo1:
    image: confluentinc/cp-zookeeper:5.3.0
    hostname: zoo1
    container_name: zoo1
    extra_hosts: 
      - "zoo2:131.247.3.206"
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
      zk_id: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      zk_server.1: 0.0.0.0:2888:3888
      zk_server.2: 131.247.3.206:2888:3888

  broker-1:
    image: confluentinc/cp-kafka:latest
    hostname: broker-1
    container_name: broker-1
    depends_on:
      - zoo1
    ports:
      - "29092:29092"
      - "9092:9092"
      - "39092:39092"
      - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 1
      #KAFKA_BROKER_RACK: rack-a
      KAFKA_ZOOKEEPER_CONNECT: 34.74.80.207:2181,131.247.3.206:2181
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_EXTERNAL1:PLAINTEXT  
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://34.74.80.207:39092
      # KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    # volumes:
    #   - ${KAFKA_SSL_SECRETS_DIR}:/etc/kafka/secrets
